spring:
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://dpg-ch5car9jvhts7knnu8cg-a.oregon-postgres.render.com:5432/my1db
    username: my1db_user
    password: s99fAu8Q2x24FCGyzrZFC3UcgrPKDKTN